apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds
    access: proxy
    url: $__env{PROMETHEUS_URL}
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: $__env{LOKI_URL}
    editable: true
